#!/usr/bin/python

import os
import raven
from yoyo import get_backend
from yoyo import read_migrations

with open(os.getenv('UID_FILE', '/sys/class/net/eth0/address'), "r") as file:
  MACHINEID = file.read().strip()

raven.Client(
  release=raven.fetch_git_sha(os.path.dirname(__file__)),
  site=MACHINEID,
  name='core-db'
)

backend = get_backend('postgres://')
migrations = read_migrations('/home/pi/core-db/migrations')

if backend._is_locked:
  backend.break_lock()
with backend.lock():
  backend.apply_migrations(backend.to_apply(migrations))

print "done migrating"
