#!/usr/bin/python

import sentry_sdk
import subprocess
from yoyo import get_backend
from yoyo import read_migrations

sentry_sdk.init()

backend = get_backend('postgres://')
migrations = read_migrations('/home/pi/core-db/migrations')
backend.apply_migrations(backend.to_apply(migrations))

subprocess.check_output('sudo systemctl restart pgbouncer.service', shell=True)

print "done migrating"
