#!/usr/bin/python

import os
import raven
import subprocess
from yoyo import get_backend
from yoyo import read_migrations

with open(os.getenv('UID_FILE', '/sys/class/net/eth0/address'), "r") as file:
  MACHINEID = file.read().strip()

raven.Client(
  release=raven.fetch_git_sha(os.path.dirname(__file__)),
  site=MACHINEID,
  name='core-db'
)

backend = get_backend('postgres://')
migrations = read_migrations('/home/pi/core-db/migrations')
backend.apply_migrations(backend.to_apply(migrations))

subprocess.check_output('sudo systemctl restart pgbouncer.service', shell=True)

print "done migrating"
